import { Oswald, Rubik } from 'next/font/google';
import './globals.css';
import '@/public/materialsymbols.css';
import Navbar from './_components/Navbar';
import Footer from './_components/Footer';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const rubik = Rubik({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700', '800', '900'],
	style: ['italic', 'normal'],
});

const oswald = Oswald({
	subsets: ['latin'],
	weight: ['700'],
});

export const metadata = {
	title: {
		template: '%s | ManageIt',
		default: 'ManageIt',
	},
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html>
			<body className={`${rubik.className} dark bg-background text-text`}>
				<Navbar />
				<ToastContainer
					position='bottom-right'
					theme='dark'
					pauseOnFocusLoss={false}
					pauseOnHover={false}
				/>
				<div className='pt-20 px-10 py-10'>{children}</div>
				<Footer />
			</body>
		</html>
	);
}
